### ISSUE TITLE
Shared Place GEDCOM v7.1 suggestions.

### ISSUE THREAD

**Issue by Norwegian-Sardines** [ric2016/shared_places#10]
I’m an advocate for augmenting GEDCOM v7.1 to include “shared places” in the standard. I’m advocating for “shared place” to have a tag name of `SPLAC` which would follow the already implemented “shared note” tag of `SNOTE` which is a change from the v5.5.1 name of `NOTE`.

What headache would it cause your module to change the current value of `_LOC` to `_SPLAC` for a future release?  Could this be a setup parameter to select either `_LOC` or `_SPLAC`?

The GEDCOM committee likes to include functional updates that are already used and supported by programs today and this could be used to support this important change to the GEDCOM Standard in the future.

thanks for your feedback

**Comment by ric2016** [comment]
[To be continued in the webtrees 2.x module](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/discussions/179) - I would have just transferred this issue but that doesn't seem to be possible between different repository owners.
