### ISSUE TITLE
GOV-field is not editable

### ISSUE THREAD

**Issue by Gunnar-GO** [ric2016/shared_places#8]
If i wanna create a shared place by button, in extended facts (right to set gov-id), i see the window comes up, i see the Name, can search the GOV but can't enter them.

I can save and accept the pretend changes, under list the shared place is there and in summary the today GOV comes up, maybe cause it is defined by place?

**Comment by ric2016** [comment]
This seems to be an issue for 2.x, therefore continued here: https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/issues/9
